version: '1'

services:
  backend:
    build: ./backend
    command: python -u "/backend/logs/views.py"
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    
  
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - backend